[basic]
save_file_dir = "./seeact_agent_files"
default_task = "Find the capitical city of France"
default_website = "https://www.google.com/"
crawler_mode = false
crawler_max_steps = 10

[agent]
input_info = ["screenshot"]
grounding_strategy = "text_choice_som"
max_auto_op = 50
max_continuous_no_op = 5
highlight = false

[openai]
# You can find your API key at https://platform.openai.com/account/api-keys.
rate_limit = -1 # Rate limit for API calls (-1 for no limit).
model = "gpt-4o" # Model name, indicating the use of GPT-4 with vision capabilities.
temperature = 0.7 # Temperature setting for GPT's responses, controlling randomness.

[oss_model]
# Reserved for future updates on open-source models.
